/**
 * The name of the command line interface.
 */
export const globalCliName = 'xscripts';

/**
 * The CLI-wide namespace that appears in logger output.
 */
export const globalLoggerNamespace = globalCliName;

/**
 * The CLI-wide namespace that appears in debugger output.
 */
export const globalDebuggerNamespace = globalCliName;

/**
 * The comment injected before each batch of auto-generated aliases.
 */
export function makeGeneratedAliasesWarningComment(spaces: number) {
  const space = ' '.repeat(spaces);

  return `${space}// ! These aliases are auto-generated by xscripts. Instead of modifying them
${space}// ! directly, consider regenerating aliases across the entire project with:
${space}// ! \`npx xscripts project renovate --regenerate-assets --assets-preset ...\`
`.trimEnd();
}
