#!/bin/sh
# {@xscripts/notExtraneous husky}

beginswith() { case $2 in "$1"*) true;; *) false;; esac; }

if beginswith 'rebase' "$GIT_REFLOG_ACTION"; then
  echo 'husky-hook::commit-msg: skipped commit-msg hook due to rebase'
  exit 0
fi

NODE_NO_WARNINGS=1 commitlint -e
# ? -xx === --skip-slow-tests --skip-slow-tests === skip really slow unit tests
if [ -z $GAC_VERIFY_SIMPLE ]; then npm run test -- -xx; fi
echo
NODE_NO_WARNINGS=1 node spellcheck-commit.cjs
